set(SDL2_FOUND TRUE)
add_library(SDL2::SDL2 INTERFACE IMPORTED)
set_target_properties(SDL2::SDL2 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_SYSROOT}/usr/include/SDL2" INTERFACE_LINK_LIBRARIES "${CMAKE_SYSROOT}/usr/lib/libSDL2.so")
