#!/usr/bin/env python3
"""Generate offline tables: pip install pypinyin==0.55.0 (build-time only)."""
from pathlib import Path
from importlib.metadata import distribution, version
from pypinyin.pinyin_dict import pinyin_dict
from pypinyin.phrases_dict import phrases_dict
from pypinyin.contrib.tone_convert import to_normal
import json
assert version('pypinyin') == '0.55.0'
root = Path(__file__).resolve().parents[1] / 'workspace/all/nextui'
def plain(s):
    return to_normal(s).replace('ü', 'v')
chars = {c: plain(v.split(',')[0]) for c, v in pinyin_dict.items()}
chars = {c: v for c, v in chars.items() if v.isascii() and v.isalpha()}
phrases = {}
for word, readings in phrases_dict.items():
    syllables = [plain(v[0]) for v in readings]
    if len(word) == len(syllables) and all(s.isascii() and s.isalpha() for s in syllables):
        if any(chars.get(ord(c)) != s for c, s in zip(word, syllables)):
            phrases[word] = ''.join(syllables)
q = lambda s: json.dumps(s, ensure_ascii=False)
lines = ['/* Generated by tools/generate-pinyin.py; pypinyin 0.55.0, MIT.',
         ' * See PINYIN-LICENSE.txt. Do not edit by hand. */',
         'static const struct { unsigned int cp; char syllable[8]; } pinyin_chars[] = {']
lines += [f'{{0x{c:x}, {q(v)}}},' for c, v in sorted(chars.items())]
lines += ['};', 'static const struct { const char *word, *key; } pinyin_phrases[] = {']
lines += [f'{{{q(w)}, {q(v)}}},' for w, v in sorted(phrases.items())]
lines += ['};', f'#define PINYIN_MAX_PHRASE_BYTES {max(len(w.encode()) for w in phrases)}']
(root / 'pinyin_data.h').write_text('\n'.join(lines) + '\n')
dist = distribution('pypinyin')
license_file = next(f for f in dist.files if str(f).endswith('/LICENSE.txt'))
(root / 'PINYIN-LICENSE.txt').write_text(dist.locate_file(license_file).read_text())
print(f'{len(chars)} characters, {len(phrases)} polyphonic phrases')
